### ISSUE TITLE
how to import ant-design-vue Only import the components you need

### ISSUE THREAD

**Issue by sixinyiyu** [easy-team/egg-vue-webpack-boilerplate#101]
the components does not effective。

"plugins": [
        "transform-object-rest-spread",
        "syntax-dynamic-import",
        "transform-object-assign",
        "transform-runtime",
        ["import", 
          { 
            "libraryName": "ant-design-vue",
            "style": "css"
          },
          "ant-design-vue"
        ]

page/index/index.vue
import Vue from 'vue';
import { Row, Col, Layout, Breadcrumb } from 'ant-design-vue';
Vue.use(Layout);

**Comment by hubcarl** [comment]
@sixinyiyu  参考这个配置试试 https://github.com/easy-team/egg-react-webpack-boilerplate/issues/11 和  https://www.yuque.com/easy-team/egg-react/babel

例子：
https://github.com/easy-team/egg-react-webpack-boilerplate/tree/antd-theme
