### ISSUE TITLE
能给一下done的配置示例吗

### ISSUE THREAD

**Issue by jimdev5277** [easy-team/egg-vue-webpack-boilerplate#102]
在文档中说了设置上传CDN的配置在done的回调中进行上传，但是没有done比较详细的示例，能否给个示例

**Comment by HiuYanChong** [comment]
[cdn配置文档](https://www.yuque.com/easy-team/easywebpack/cdn)
```js
// ${app_root}/webpack.config.js
const UPLOAD_CDN = process.env.UPLOAD_CDN;
module.exports = {
  ......
  cdn: 'http://xxx.cdn.com/public/',
  done () {
    // upload static file to cdn: http://xxx.cdn.com
    if (UPLOAD_CDN)  {
       // 使用默认配置时，静态资源在 ${app_root}/public 下
      //  使用 cdn 服务商提供的接口将静态资源上传到 cdn
    }
  }
}
```

**Comment by jimdev5277** [comment]
> [cdn配置文档](https://www.yuque.com/easy-team/easywebpack/cdn)
> 
> ```js
> // ${app_root}/webpack.config.js
> const UPLOAD_CDN = process.env.UPLOAD_CDN;
> module.exports = {
>   ......
>   cdn: 'http://xxx.cdn.com/public/',
>   done () {
>     // upload static file to cdn: http://xxx.cdn.com
>     if (UPLOAD_CDN)  {
>        // 使用默认配置时，静态资源在 ${app_root}/public 下
>       //  使用 cdn 服务商提供的接口将静态资源上传到 cdn
>     }
>   }
> }
> ```

这个我在文档中已经看到了，能发一下里面的回调函数中的参数说明，没有参数说明不知里面的参数具体是什么

**Comment by jimdev5277** [comment]
> done有两个回调参数。
> 戳[这里](https://github.com/easy-team/webpack-tool/blob/master/lib/tool.js#L134)

好的 非常感谢
