### ISSUE TITLE
eslint: Parsing error: Adjacent JSX elements must be wrapped in an enclosing tag

### ISSUE THREAD

**Issue by yaoleia** [easy-team/egg-vue-webpack-boilerplate#103]
VUE文件 怎么被识别成了jsx呢?

eslint报错：Parsing error: Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>?

  10 | </template>
  11 | 
> 12 | <script type="text/babel">
     | ^
  13 | 	export default {
  14 | 		data() {
  15 | 			return {

**Comment by HiuYanChong** [comment]
我本地无法复现，
看起来和这个 [issue](https://github.com/vuejs/eslint-plugin-vue/issues/186#issuecomment-329426553) 一样
[解决方案](https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error)

**Comment by yaoleia** [comment]
多谢@ HiuYanChong
