### ISSUE TITLE
页面绑定的数据render后通过script标签把数据存在window.__INITIAL_STATE__上，怎么可以不要绑定，或者怎么配置打包到js文件中，不要出现在html页面中。数据很多的时候看起来不太好

### ISSUE THREAD

**Issue by gongdf** [easy-team/egg-vue-webpack-boilerplate#108]

**Comment by hubcarl** [comment]
不能去掉， 走 ssr 模式，必须要 window.__INITIAL_STATE， 可以去了解一下 vue/react 的 ssr 原理

**Comment by gongdf** [comment]
> 不能去掉， 走 ssr 模式，必须要 window.__INITIAL_STATE， 可以去了解一下 vue/react 的 ssr 原理

好的，谢谢。
