### ISSUE TITLE
当以renderClient运行的时候会报错

### ISSUE THREAD

**Issue by exment** [easy-team/egg-vue-webpack-boilerplate#110]
当以renderClient运行的时候会报错 当前页面的VUE实例的data定义的数据没找到,
Property or method “xxx” is not defined on the instance but referenced during render.
临时解决方案：
在\egg-vue-webpack-boilerplate-master\node_modules\vue-entry-loader\lib\web.js中添加
if(vm.data != undefined){
    Object.assign(data,vm.data())
}
希望官方能够解决

**Comment by hubcarl** [comment]
@exment  已修复 https://github.com/easy-team/vue-entry-loader/issues/1
