### ISSUE TITLE
npm install 和npm run dev后直接报错，vue文件缺少loader

### ISSUE THREAD

**Issue by wumingxiaozu1990** [easy-team/egg-vue-webpack-boilerplate#113]
npm install 和npm run dev后直接报错，view文件下vue文件缺少loader
ERROR in ./app/web/page/admin/home/router/index.js 22:15
Module parse failed: Unexpected token (22:15)
You may need an appropriate loader to handle this file type.
|       path: '/article/add',
|       component: function component() {
>         return import('../view/write/index.vue');
|       }
|     }, {

**Comment by TerryLam2010** [comment]
我也是，老哥你这边有解决嘛？

**Comment by hubcarl** [comment]
see https://github.com/webpack/webpack/issues/8656

**Comment by whidy** [comment]
我手动安装了一下这个版本的webpack，临时可以解决，不知道还有没有更好的解决办法。

```
npm install webpack@4.28.4 -D
```
