### ISSUE TITLE
文档中用于客户端渲染的 layout.html 路径好像不对？

### ISSUE THREAD

**Issue by ColinLeo** [easy-team/egg-vue-webpack-boilerplate#114]
文档：[Egg + Vue 工程化解决方案 - 从零开始](https://www.yuque.com/easy-team/egg-vue/start)

在 [2. 初始化 egg 项目](https://www.yuque.com/easy-team/egg-vue/start#8guxqa)，'新建 ${app_root}/app/view/layout.html 文件' 中 'layout.html' 是不是应该在 `/app/web/view/layout.html`？

按照文档一步步操作，切换到客户端渲染时会报错

```bash
nodejs.Error: render function or template not defined in component: anonymous
```

参考了 [element-admin](https://github.com/easy-team/egg-vue-webpack-boilerplate/tree/element-admin)，将 'layout.html' 移到 `/app/web/view/layout.html` 后，可以正常运行。

---
另外两个小问题

- [编写 Node 端代码](https://www.yuque.com/easy-team/egg-vue/start#8m9fcn) 中 `server` 和 `client` 文案相同。
![image](https://user-images.githubusercontent.com/22308897/52623108-6eeea480-2ee6-11e9-9955-bbeced39f51d.png)

- [编写前端 vue 代码](https://www.yuque.com/easy-team/egg-vue/start#525ysn) ，`app/web/page/home/home.js` 中 `EASY_ENV_IS_NODE` 变量在该文档中没有出现；会导致 /client 无法使用客户端渲染。
是否可以考虑改为传参或单独文件？
e.g.
```js
// app/web/page/home/home-client.js
import Home from './home.vue';
import clientRender from '~/app/web/framework/vue/entry/client.js';
export default clientRender({ ...Home });

// app/controller/home.js
await ctx.renderClient('home/home-client.js', { message: 'egg vue renderClient' });
```

**Comment by hubcarl** [comment]
layout.html 路径问题由 egg-view-vue-ssr  的 layout 配置指定， 默认是 ${app_root}/app/view/layout.html   可以看一下 config.default.js 的 vuessr 的layout 配置

**Comment by hubcarl** [comment]
EASY_ENV_IS_NODE 这个是 easywebpack 同DefinePlugin 内置的全局变量
