### ISSUE TITLE
克隆下来的代码，install后无法启动

### ISSUE THREAD

**Issue by SFight** [easy-team/egg-vue-webpack-boilerplate#116]
不支持尖角号的写法，不知道是为什么，代码无法启动
<img width="648" alt="WX20190320-154339@2x" src="https://user-images.githubusercontent.com/9443012/54667364-2058a980-4b27-11e9-90fb-9a764e51c6cf.png">

**Comment by hubcarl** [comment]
@SFight see https://github.com/webpack/webpack/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc and https://github.com/wix/yoshi/pull/1071  

解决办法： npm install webpack@4.28.4 -D

**Comment by hubcarl** [comment]
目前，底层我先锁住 webpack 为 4.28.4

**Comment by SFight** [comment]
> @SFight see [webpack/webpack#8656](https://github.com/webpack/webpack/issues/8656) and [wix/yoshi#1071](https://github.com/wix/yoshi/pull/1071)
> 
> 解决办法： npm install webpack@4.28.4 -D

多谢，可以了。

**Comment by SFight** [comment]
@hubcarl 可以了，多谢。
