### ISSUE TITLE
easywebpack打包后js文件过大

### ISSUE THREAD

**Issue by wpbeio** [easy-team/egg-vue-webpack-boilerplate#117]
即使是element-admin这个骨架项目build过后也会报admin.js文件过大, 主文件713k
这个应该是一个通用问题,也按照配置将  devtool: 'source-map' 启用压缩也没有作用.使用npm build 
本身就是prod模式了.

**Comment by hubcarl** [comment]
@wpbeio  element 压缩后本身有 500KB ，再加上 vue 套件，差不多这么大。如果开启 gzip （nginx 或者 egg-static) 预计 200KB。 可以看看 element 按需加载， 具体配置结合 element 按需加载 + https://www.yuque.com/easy-team/egg-react/antd 实现
