### ISSUE TITLE
npm run build 报错

### ISSUE THREAD

**Issue by 5oftsky** [easy-team/egg-vue-webpack-boilerplate#118]
![image](https://user-images.githubusercontent.com/8733310/56118007-f49cd800-5f9b-11e9-9548-6fb12eb76e7d.png)

使用了 pug 模板，本地开发的时候没问题，线上服务部署，执行 npm run build 后 报错，这是什么问题呢？

**Comment by hubcarl** [comment]
@5oftsky  我看关闭issue，找到原因不，是什么导致的

**Comment by 5oftsky** [comment]
> @5oftsky 我看关闭issue，找到原因不，是什么导致的

这个问题很奇怪，我之前一直能使用pug模板，本地没报错，过了很长时间重新clone，安装 node modules 就报错了，后来配置了 pug-plain-loader 可以了，之前只是用了pug。
