### ISSUE TITLE
请问为什么 我远程查询 title keywords 赋值了 传给组件不生效

### ISSUE THREAD

**Issue by mei2015** [easy-team/egg-vue-webpack-boilerplate#120]
![image](https://user-images.githubusercontent.com/10136065/59679651-fc7a3200-9201-11e9-80fe-6518d5ac2b55.png)
为什么 这个地方异步查询出来的 无法赋值过去

**Comment by hubcarl** [comment]
@mei2015 目前 title 和 keyword 只在 render 生效，直接是服务端渲染出来的

**Comment by mei2015** [comment]
> @mei2015 目前 title 和 keyword 只在 render 生效，直接是服务端渲染出来的

那我怎么设置啊

**Comment by mei2015** [comment]
> @mei2015 目前 title 和 keyword 只在 render 生效，直接是服务端渲染出来的

![image](https://user-images.githubusercontent.com/10136065/59680191-562f2c00-9203-11e9-8f5c-96f7e1077019.png)
还有ma麻烦问下 你这个在哪定义的呢  怎样实现后台查询出来 而不是写死呢？？

**Comment by hubcarl** [comment]
@mei2015  你直接在 render 的第二个参数传递相关值给页面，layout 那里传递一下就行

**Comment by mei2015** [comment]
> @mei2015 你直接在 render 的第二个参数传递相关值给页面，layout 那里传递一下就行

大大能不能详细说下， 我不太懂刚上手，我现在在做后台

![image](https://user-images.githubusercontent.com/10136065/59680519-187ed300-9204-11e9-8614-bcac0e4b5306.png)
我现在就想动态改变这些值， 你是说在这样 查询吗

“ render 的第二个参数” 这个是哪里啊

**Comment by mei2015** [comment]
> @mei2015 你直接在 render 的第二个参数传递相关值给页面，layout 那里传递一下就行

![image](https://user-images.githubusercontent.com/10136065/59680883-1d905200-9205-11e9-86f4-cba88360fb40.png)
你是说的这个吗

**Comment by hubcarl** [comment]
@mei2015 用的哪个分支？

**Comment by mei2015** [comment]
> @mei2015 用的哪个分支？

https://github.com/easy-team/egg-vue-webpack-boilerplate这个

**Comment by hubcarl** [comment]
@mei2015 这个问题我需要看一下，明天我试一下

**Comment by mei2015** [comment]
> @mei2015 这个问题我需要看一下，明天我试一下

好的 谢谢了 麻烦你看下

**Comment by hubcarl** [comment]
@mei2015 可以这样
```
  computed: {
    title() {
      return this.$store.state.title;
    }
  }
```

```
<AdminLayout :title="title">
    <transition name="fade" mode="out-in">
      <router-view></router-view>
    </transition>
  </AdminLayout>
```

**Comment by mei2015** [comment]
> @mei2015 可以这样
> 
> ```js
>   computed: {
>     title() {
>       return this.$store.state.title;
>     }
>   }
> ```
> 
> ```
> <AdminLayout :title="title">
>     <transition name="fade" mode="out-in">
>       <router-view></router-view>
>     </transition>
>   </AdminLayout>
> ```

那 我的 数据在哪 查询出来呢，在哪个生命周期 调用 查询数据

**Comment by hubcarl** [comment]
在 node AdminController 里面请求数据呀

- egg-vue-webpack-boilerplate/app/controller/admin/admin.js

```
module.exports = class AdminController extends egg.Controller {
  async home(ctx) {
    const url = ctx.url.replace(/\/admin/, '');
    await ctx.render('admin/home/home.js', { ctx, url, title: '设置标题' });
  }
}
```

**Comment by mei2015** [comment]
> 在 node AdminController 里面请求数据呀
> 
> * egg-vue-webpack-boilerplate/app/controller/admin/admin.js
> 
> ```
> module.exports = class AdminController extends egg.Controller {
>   async home(ctx) {
>     const url = ctx.url.replace(/\/admin/, '');
>     await ctx.render('admin/home/home.js', { ctx, url, title: '设置标题' });
>   }
> }
> ```

嗯  谢谢了 刚才没有看全 你的回答 明白了 3q 感谢

**Comment by mei2015** [comment]
> 在 node AdminController 里面请求数据呀
> 
> * egg-vue-webpack-boilerplate/app/controller/admin/admin.js
> 
> ```
> module.exports = class AdminController extends egg.Controller {
>   async home(ctx) {
>     const url = ctx.url.replace(/\/admin/, '');
>     await ctx.render('admin/home/home.js', { ctx, url, title: '设置标题' });
>   }
> }
> ```

完美解决 谢谢了！

**Comment by mei2015** [comment]
> > 在 node AdminController 里面请求数据呀
> > 
> > * egg-vue-webpack-boilerplate/app/controller/admin/admin.js
> > 
> > ```
> > module.exports = class AdminController extends egg.Controller {
> >   async home(ctx) {
> >     const url = ctx.url.replace(/\/admin/, '');
> >     await ctx.render('admin/home/home.js', { ctx, url, title: '设置标题' });
> >   }
> > }
> > ```
> 
> 嗯 谢谢了 刚才没有看全 你的回答 明白了 3q 感谢

大大 有没有qq 群呀

**Comment by hubcarl** [comment]
@mei2015  433207205 请填写相关备注

**Comment by sixinyiyu** [comment]
@hubcarl  请问，如果是在 layout/index 目录里使用vuex ，怎么挂在到vue上；那title 参数也是按上面这样处理吗？
