### ISSUE TITLE
sass无法加载

### ISSUE THREAD

**Issue by imhazige** [easy-team/egg-vue-webpack-boilerplate#124]
使用分支 https://github.com/easy-team/egg-vue-webpack-boilerplate/tree/feature/green/multi

报错
ERROR in ./app/web/page/admin/index.vue?vue&type=style&index=0&lang=scss& (./node_modules/vue-loader/lib??vue-loader-options!./app/web/page/admin/index.vue?vue&type=style&index=0&lang=scss&) 14:0
Module parse failed: Unexpected character '@' (14:0)
You may need an appropriate loader to handle this file type.
| 
| 
> @import "./index.scss";
| 

源码
https://github.com/imhazige/egg-vue-webpack-boilerplate/blob/vue-multi-mongoose-graphql/app/web/page/admin/index.vue#L13

**Comment by imhazige** [comment]
@hubcarl

**Comment by hubcarl** [comment]
@imhazige  需要开启 sass 配置 

```
// ${root}/webpack.config.js
module.exports = {
  plugins: {
   scss: true
  }
}
```

// ${root}/package.json 的 devDependencies 增加如下依赖
"node-sass": "^4.5.3",
"sass-loader": "^6.0.6",

**Comment by janmi** [comment]
> @imhazige 需要开启sass配置
> 
> ```
> // ${root}/webpack.config.js
> module.exports = {
>   loaders: {
>    scss: true
>   }
> }
> ```
> 
> ```
> // ${root}/package.json 的 devDependencies 增加如下依赖， 同时 npm install 一下
> "node-sass": "^4.5.3",
> "sass-loader": "^6.0.6",
> ```

按照这个配置之后无法正常的编译 scs；在 init 的时候已经选择了 sass了， 配置上不会主动设置这个配置吗？

**Comment by imhazige** [comment]
还是有问题，这eggjs还是算了，还是用meteor。
