### ISSUE TITLE
App节点被重复渲染

### ISSUE THREAD

**Issue by icewind7030** [easy-team/egg-vue-webpack-boilerplate#125]
版本：4.4.7
平台：Mac os
浏览器：Chrome 75.0.3770.142
问题：直接运行master上的代码，就可以看到，SSR已经渲染好的html内容被重新渲染一遍。

如下图可以看到，在设置body break on subtree modifications后，即使ssr返回的html string内容正确，`#app`节点依然被再次插入html，并且会移除之前已经存在的`#app`节点？

请问这是vue SSR渲染的正确表现吗？
![render](https://easyreadfs.nosdn.127.net/web/trunk/1563885393071/wx20190723-203618.png)

**Comment by hubcarl** [comment]
@icewind7030 这个是有问题的，app/web/component/layout/default.js 这里不应该写 id="app", 这个直接写在 app/web/component/layout/layout.js 里，只在服务端生成 id="app"

**Comment by icewind7030** [comment]
@hubcarl 确定这么改没问题吗，现在ssr出来的内容里面好像#app节点为空了，变成了客户端渲染？
![csr](https://easyreadfs.nosdn.127.net/web/trunk/1564136712196/wx20190726-182432.png)

**Comment by hubcarl** [comment]
@icewind7030  有问题，我再看看

**Comment by icewind7030** [comment]
@hubcarl 好像还是不对额，这下ssr的内容变成2个#app嵌套了，源码我也研究过，也没找到问题
![image](https://user-images.githubusercontent.com/7500226/61949733-5a0e5500-afde-11e9-9d05-464037a3dd00.png)

**Comment by hubcarl** [comment]
![image](https://user-images.githubusercontent.com/4983042/61951713-6d242380-afe4-11e9-8dfa-5b292adbd379.png)

@icewind7030  我这里只有一个，是不是改错了，你看一下最新代码。

**Comment by hubcarl** [comment]
@icewind7030 这个问题还需要再确认一下

**Comment by hubcarl** [comment]
@icewind7030 更新一下 vue-entry-loader 插件 see：https://github.com/easy-team/vue-entry-loader/commit/d78b69b

原因是 Vue SSR 判断是 hydrate 是根据 mount 的 app 节点上是否 data-server-rendered , 当前的服务端 render 是整个 HTML 节点，data-server-rendered 节点是标注在 HTML 标签上， 但 mount 是在 app 上，获取不到 data-server-rendered，最终走了重新渲染。 目前解决方案有三种：

- 方法一：`app.$mount(root, hydrate)` 传递第二个参数， 如果是 SSR，传true，否则 false 或者不传。其中 vue-entry-loader 已经默认自动识别，请重新安装插件。
- 方法二：如果是服务端渲染，直接在 id=“app” 加上 data-server-rendered=“true” 即可
- 方式三：layout 由其他模板引擎渲染，服务端只渲染 body 里面内容，这样 data-server-rendered=“true” 会自动加到 app 节点上。

**Comment by icewind7030** [comment]
@hubcarl 确实是这个问题，感谢解答
