### ISSUE TITLE
线上部署问题，使用nginx部署项目，无法加载clientrender的js代码

### ISSUE THREAD

**Issue by wade-yifeng** [easy-team/egg-vue-webpack-boilerplate#126]
目前在docker环境下通过nginx+egg-vue构建的项目部署，但目前无法访问clientrender部分页面，只加载了layout，vue并没有注入app，本地运行(npm run build, npm start)没有这个问题，配置了vuessr如下：
`config.vuessr = {
    layout: path.join(appInfo.baseDir, 'app/web/page/layout.html'),
    renderOptions: {
      // 告诉 vue-server-renderer 去 app/view 查找异步 chunk 文件
      basedir: path.join(appInfo.baseDir, 'app/view')
    }
  }`
同时docker容器中也确认共享了app/view文件夹，nginx只做了代理转发，如下：
`location / {
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://node-app;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }`

**Comment by wade-yifeng** [comment]
格式化一下配置：
`config.vuessr = { 
layout: path.join(appInfo.baseDir, 'app/web/page/layout.html'), 
renderOptions: { 
// 告诉 vue-server-renderer 去 app/view 查找异步 chunk 文件 
basedir: path.join(appInfo.baseDir, 'app/view') 
} }`
`location / { 
proxy_http_version 1.1; 
proxy_set_header X-Real-IP $remote_addr; 
proxy_pass http://node-app; 
proxy_set_header Upgrade $http_upgrade; 
proxy_set_header Connection 'upgrade'; 
proxy_set_header Host $host; 
proxy_cache_bypass $http_upgrade; 
}`

**Comment by hubcarl** [comment]
@wade-yifeng 请确认打包后构建资源有包含进去，除了 Node 代码，还需要包括 app/view, config/manifest.json, public 目录构建的文件

**Comment by wade-yifeng** [comment]
已解决
