### ISSUE TITLE
npm run dev 报少 Can't resolve 'service-worker-register' 

### ISSUE THREAD

**Issue by doocal** [easy-team/egg-vue-webpack-boilerplate#128]
ERROR in ./app/web/page/home/index.vue?vue&type=script&lang=js& (./node_modules/thread-loader/dist/cjs.js??ref--0-0!./node_modules/babel-loader/lib??ref--0-1!./node_modules/vue-loader/lib??vue-loader-options!./app/web/page/home/index.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'service-worker-register' in 'E:\JS\egg-vue-webpack-boilerplate\app\web\page\home'

**Comment by hubcarl** [comment]
@doocal npm install service-worker-register --save

**Comment by doocal** [comment]
egg-vue-webpack-boilerplate 的master分支；

**Comment by hubcarl** [comment]
@doocal 好的
