### ISSUE TITLE
feature/green/spa分支npm run build报错

### ISSUE THREAD

**Issue by 521314xiongCheng** [easy-team/egg-vue-webpack-boilerplate#133]
![image](https://user-images.githubusercontent.com/54136501/67745997-8499ff00-fa60-11e9-9e4e-ccdb725a1ee7.png)

**Comment by hubcarl** [comment]
@521314xiongCheng  什么都没改报错？还是加了什么配置？ 这里验证是 可以的

**Comment by hubcarl** [comment]
重复安装，已收到回复OK
