### ISSUE TITLE
目录asset下的音频文件使用url-loader无法打包到public目录下

### ISSUE THREAD

**Issue by lwadsy** [easy-team/egg-vue-webpack-boilerplate#138]
{ urlmedia: { 
      options: { 
        limit: 2048,
        name: '[name].[hash:7].[ext]'
      } 
    }

**Comment by hubcarl** [comment]
好的，我先看看

**Comment by lwadsy** [comment]
> 好的，我先看看

字体库也不行，目前测试看只能是三个目录css、images、js可以build出来

**Comment by hubcarl** [comment]
@lwadsy  这个构建没有问题，会构建到 public 目录

![image](https://user-images.githubusercontent.com/4983042/70860126-75abd500-1f58-11ea-8093-74cd4a02c5aa.png)


https://github.com/easy-team/egg-vue-webpack-boilerplate/commit/1e1cdc55206153f9265147ead1895e3bf6f3bc68

**Comment by lwadsy** [comment]
> @lwadsy 视频这些二进制文件构建没有问题，会构建到 public 目录
> 
> ![image](https://user-images.githubusercontent.com/4983042/70860126-75abd500-1f58-11ea-8093-74cd4a02c5aa.png)
> 
> [1e1cdc5](https://github.com/easy-team/egg-vue-webpack-boilerplate/commit/1e1cdc55206153f9265147ead1895e3bf6f3bc68)

我使用的easy-cli构建的egg+vue多页面服务端渲染的模板

**Comment by lwadsy** [comment]
非常感谢，现在知道原因了，我只是把文件放到目录下，但是没有引用，打包的时候没打包
