### ISSUE TITLE
vue服务器端渲染的时候，controller中是否可以通过重定向的方式到页面

### ISSUE THREAD

**Issue by lwadsy** [easy-team/egg-vue-webpack-boilerplate#139]
vue服务器端渲染的时候，controller中是否可以通过重定向的方式到页面，有个场景：get到controller的的一个方法进行服务器端渲染，但浏览器地址栏还有参数，我想通过重定向的方式去掉get过来的参数信息

**Comment by HiuYanChong** [comment]
框架基于 egg. 
egg 重定向文档戳[这里](https://eggjs.org/en/basics/router.html#redirection)
egg 重定向安全策略戳[这里](https://eggjs.org/en/basics/controller.html#redirect)
