### ISSUE TITLE
想要实现i18n的热重载 该怎么做？

### ISSUE THREAD

**Issue by Lunziyuan** [easy-team/egg-vue-webpack-boilerplate#140]
Node Vue SSR 框架
i18n是读取的本地文件，线上发布之后，希望能够实时的更新多语言文案。
正式打包之后，该怎么实现多语言文件的热更新呢？

**Comment by hubcarl** [comment]
@Lunziyuan 多语言内容你可以从Node当作数据传给页面处理。 至于多语言内容你可以存储数据库或者定时拉取也可以

**Comment by Lunziyuan** [comment]
感谢 问题解决了
