### ISSUE TITLE
Unexpected end of JSON input while parsing near '...,"gulp-concat":"lates'

### ISSUE THREAD

**Issue by houjl001** [easy-team/egg-vue-webpack-boilerplate#141]
npm install 报错

**Comment by willworks** [comment]
node 版本多少？看起来是识别不了 ES6 的解构赋值语法

**Comment by willworks** [comment]
@houjl001 node 版本多少？看起来是识别不了 ES6 的解构赋值语法

**Comment by houjl001** [comment]
> @houjl001 node 版本多少？看起来是识别不了 ES6 的解构赋值语法

8.11.2

**Comment by willworks** [comment]
@houjl001 试试看 `npm cache clean --force` 再执行安装，再不行的话你贴更多的错误信息出来下
