### ISSUE TITLE
服务端渲染没有使用layout.html

### ISSUE THREAD

**Issue by FoxDaxian** [easy-team/egg-vue-webpack-boilerplate#142]
要求服务端渲染，执行render方法，代码：

```javascript
class PostController extends Controller {
    async create() {
        const {ctx} = this;
        await ctx.render('index.js');
    }
}
```

渲染结果如下：
![image](https://user-images.githubusercontent.com/19708789/72036644-6c532580-32d6-11ea-9323-45c2509cd5a3.png)

没有注入到客户端中，也没有插入编译后的js进行客户端激活。

麻烦帮忙看下

**Comment by hubcarl** [comment]
@FoxDaxian  服务端渲染不会使用这个 layout.html，需要自己写个 vue 的 layout 组件 见：
https://github.com/easy-team/egg-vue-webpack-boilerplate/blob/master/app/web/page/index/index.vue 和  https://github.com/easy-team/egg-vue-webpack-boilerplate/tree/master/app/web/component/layout

**Comment by FoxDaxian** [comment]
layout加载规则呢?

**Comment by hubcarl** [comment]
@FoxDaxian  看这个简单的 https://github.com/easy-team/egg-vue-webpack-boilerplate/blob/master/app/web/page/test/test.vue，上面那个是简单的包了一下，看 framework下面
