### ISSUE TITLE
多页面服务端渲染如何动态渲染页面？

### ISSUE THREAD

**Issue by zhengtulymGh** [easy-team/egg-vue-webpack-boilerplate#147]
比较常见的需求是一些文章详情，页面很多，需要基于一个模板和路由参数填充数据后动态渲染，项目中没有这种例子。管理后台的那个是服务端单页面渲染的。

**Comment by hubcarl** [comment]
@zhengtulymGh  master index， category 就是多页面直接渲染的例子
