### ISSUE TITLE
egg-vue vs ves 区别

### ISSUE THREAD

**Issue by usherwong** [easy-team/egg-vue-webpack-boilerplate#148]
想问下egg-vue和ves的差异，看着都是Egg + vue 都支持ssr 和 csr ，都支持js和ts。

**Comment by hubcarl** [comment]
@usherwong 本质没有差异， ves 是基于 egg 的上层框架，同时把 egg vue ssr 相关的全部内置了，简化了一些配置

**Comment by hubcarl** [comment]
@bi-kai  推荐用 egg-vue-webpack 系列
