### ISSUE TITLE
报错 yarn 和npm 安装会报错， cnpm 正常

### ISSUE THREAD

**Issue by simpleET** [easy-team/egg-vue-webpack-boilerplate#153]
win10 64位  node 14.2  
尝试降低 imagemin-webpack-plugin 的版本还是报错
报错信息如下：
error H:\SSR\egg-vue-webpack-boilerplate-feature-green-spa\node_modules\gifsicle: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: H:\SSR\egg-vue-webpack-boilerplate-feature-green-spa\node_modules\gifsicle
Output:
‼ getaddrinfo ENOENT raw.githubusercontent.com
  ‼ gifsicle pre-build test failed
  i compiling from source
  × Error: Command failed: C:\Windows\system32\cmd.exe /s /c "autoreconf -ivf"
'autoreconf' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

    at H:\SSR\egg-vue-webpack-boilerplate-feature-green-spa\node_modules\bin-build\node_modules\execa\index.js:231:11

**Comment by hubcarl** [comment]
@simpleET https://www.yuque.com/easy-team/easywebpack/problem#c0325d69
