### ISSUE TITLE
vue-router children路由无法使用

### ISSUE THREAD

**Issue by DragWeb** [easy-team/egg-vue-webpack-boilerplate#77]
很方便复现，直接在router中加上children节点，无法访问到children路由。
是BUG吗？

**Comment by hubcarl** [comment]
这个你可以研究一下getMatchedComponents： https://github.com/hubcarl/egg-vue-webpack-boilerplate/blob/master/app/web/framework/vue/app.js#L35:48

**Comment by DragWeb** [comment]
好的，谢谢

**Comment by fyAgent** [comment]
链接挂掉了啊

**Comment by hubcarl** [comment]
@fyAgent  已修改
