### ISSUE TITLE
在webpack.config.js配置publicPath问题

### ISSUE THREAD

**Issue by jackwsy** [easy-team/egg-vue-webpack-boilerplate#80]
window系统配置，mac没问题
在webpack.config.js 新增参数
 publicPath:"/dist",
结果build时报错，报错如下：
![image](https://user-images.githubusercontent.com/13105469/43875592-8e71a1c4-9bc3-11e8-9ea1-da5ffcb3dc92.png)

**Comment by laureler** [comment]
大神，你好。我关注egg.js几天了，看文档希望修改publicPath，静态资源路径。但是发现当我使用easy-team出的项目骨架修改webpack.config.js文件的时候，发现静态资源映射永远都是404，打断点发现应该是我在config中配置的config.default.js中static的静态资源映射配置不起作用。想知道我时候是那个地方忘记了修改。
项目骨架地址是这个：easy-team/egg-vue-webpack-boilerplate
参考文档路径为 ：常见问题 · 语雀
希望达到的结果是：我修改静态资源路径为 /static/   ，但是按照文档来直接就回出现404错误。

**Comment by laureler** [comment]
最近跟踪代码发现，修改publicPath不能够成功的根本原因在于，egg-webpack插件在config.default.js中，默认使用了 
![image](https://user-images.githubusercontent.com/26224399/49326711-59c5d300-f591-11e8-8240-8fcd9f9aebaa.png)
，当我们修改了webpack.config.js中的publicPath以及egg-static的静态资源映射时，
开发模式下，是不能够访问到静态资源的，因为webpack依然在代理路径为public的静态资源，所以在

https://www.yuque.com/easy-team/egg-vue/about#glrguf
常见问题中，还希望能够将对应的开发模式下的配置添加上，以免产生困惑。
//config.default.js文件修改代理路径
![image](https://user-images.githubusercontent.com/26224399/49326738-ae694e00-f591-11e8-9cea-185d2178f5e6.png)

**Comment by lzs123** [comment]
> 最近跟踪代码发现，修改publicPath不能够成功的根本原因在于，egg-webpack插件在config.default.js中，默认使用了
> ![image](https://user-images.githubusercontent.com/26224399/49326711-59c5d300-f591-11e8-8240-8fcd9f9aebaa.png)
> ，当我们修改了webpack.config.js中的publicPath以及egg-static的静态资源映射时，
> 开发模式下，是不能够访问到静态资源的，因为webpack依然在代理路径为public的静态资源，所以在
> 
> https://www.yuque.com/easy-team/egg-vue/about#glrguf
> 常见问题中，还希望能够将对应的开发模式下的配置添加上，以免产生困惑。
> //config.default.js文件修改代理路径
> ![image](https://user-images.githubusercontent.com/26224399/49326738-ae694e00-f591-11e8-9cea-185d2178f5e6.png)
修改了还是没用呀，还是会出现@jackwsy一样的报错

**Comment by lzs123** [comment]
> window系统配置，mac没问题
> 在webpack.config.js 新增参数
> publicPath:"/dist",
> 结果build时报错，报错如下：
> ![image](https://user-images.githubusercontent.com/13105469/43875592-8e71a1c4-9bc3-11e8-9ea1-da5ffcb3dc92.png)

。。我是mac上报错了

**Comment by hubcarl** [comment]
@laureler  文档已补充
