### ISSUE TITLE
spa component中样式 最终被输出到public/css目录中没有添加前置目录 并且会输出空css

### ISSUE THREAD

**Issue by oooowl** [easy-team/egg-vue-webpack-boilerplate#81]
例如app目录下spa
某页面
/web/page/app/component/page1.vue

dist
/public/css/1.xxxxxx.css

**Comment by hubcarl** [comment]
目前 css 文件都不会添加前置目录，css 为空问题 https://github.com/webpack/webpack/issues/7300
