### ISSUE TITLE
抱歉，强迫症犯了，箭头处应该是拼写错误吧

### ISSUE THREAD

**Issue by gavin1657919948** [easy-team/egg-vue-webpack-boilerplate#88]
![_20180921161010](https://user-images.githubusercontent.com/29375431/45868644-e5183080-bdb8-11e8-9862-e3d40658a3ea.png)
![_20180921160907](https://user-images.githubusercontent.com/29375431/45868658-eb0e1180-bdb8-11e8-8cd1-d5c099c1c5fc.png)

**Comment by hubcarl** [comment]
@gavin1657919948 是写错了，我改一下
