### ISSUE TITLE
打包文件太大

### ISSUE THREAD

**Issue by lcsoftware** [easy-team/egg-vue-webpack-boilerplate#89]
easy build production 部署到线上，打包后的app.d682f61d.js （1.1M ）文件及各个单页面(200K以上)，这文件里都是什么，怎么会这么大呢，需要修改webpack.config.js哪些配置吗？

**Comment by symenywong** [comment]
打包文件过大,经测试对比发现应该为引入vue UI框架造成;
例如 iview 框架, 对比测试在使用多页面渲染时, 关闭已引用 UI框架, 代码体积可减少至几十kb , 开启 iview 后页面体积文字在600Kb-700kb左右, 
但是此时使用 iview 按需引入会跟 webpack.config.js 冲突导致编译报错, 所以
1. 如何正确使用外部框架按需引入(如 iview, element UI)
2. 外部插件 CDN 如(iview css样式文件)分离;
可以明显减少代码体积;

**Comment by hubcarl** [comment]
具体怎么使用，可以看看各种 UI 框架的按需引入方式
