### ISSUE TITLE
多页面渲染如何按需引用iview组件

### ISSUE THREAD

**Issue by easonzhuyi** [easy-team/egg-vue-webpack-boilerplate#90]
单页面渲染用了iview官方的babel-plugin-import正常，多页渲染报错：" Unexpected token import，try client render"。但是全局引用能正常渲染。

**Comment by momtboy** [comment]
@easonzhuyi 按需加载，怎么提取公用css的呢？兄台知道不？

**Comment by easonzhuyi** [comment]
> @easonzhuyi 按需加载，怎么提取公用css的呢？兄台知道不？

@momtboy iview组件的结构就没有style目录（antd有），应该只能全局引入

**Comment by sixinyiyu** [comment]
ant-design-vue how to use for server render?

**Comment by hubcarl** [comment]
see https://github.com/easy-team/egg-vue-webpack-boilerplate/issues/29

iview css 必须全部引入
