### ISSUE TITLE
vue的ssr中store并没有同步

### ISSUE THREAD

**Issue by huangpiqiao** [easy-team/egg-vue-webpack-boilerplate#91]
ssr中服务端的store和客户端的store并没有同步

**Comment by hubcarl** [comment]
@huangpiqiao 请提供更详细的信息 ，可以看看最新的单页面实现方案：https://github.com/easy-team/egg-vue-webpack-boilerplate/tree/feature/green/spa

**Comment by RobinMao** [comment]
> ssr中服务端的store和客户端的store并没有同步

@huangpiqiao  
是不是调用renderClient没有渲染出来？
看下你代码中是不是有这段代码?

> https://github.com/easy-team/egg-vue-webpack-boilerplate/blob/c5104731b353e9d5e6cee4196f6098cdc63c3009/app/web/framework/vue/entry/client.js

把这里代码动一下，应该可以搞定。
```js
if (options.store) {
    options.store.replaceState({...state, ...options.store.state});
  } else {
    options.data = { ...state, ...options.data };
  }
```
