### ISSUE TITLE
热更新回数多了 内存降不下来 最终导致重新编译

### ISSUE THREAD

**Issue by shusc24** [easy-team/egg-vue-webpack-boilerplate#92]
项目就是这个demo项目 不过配置变了 其实之前用的 react 版本也是 react那个版本项目大了 热编译只要一两次就会 到上限 但是好像webpack3.0 那个情况好点 内存会降下来  我贴下我的 package.json 代码  项目代码就是原始代码

[package.zip](https://github.com/hubcarl/egg-vue-webpack-boilerplate/files/2426615/package.zip)

[报错任务管理器截图.zip](https://github.com/hubcarl/egg-vue-webpack-boilerplate/files/2426618/default.zip)

**Comment by hubcarl** [comment]
@shusc24 该问题已找到原因，今天已经修复，重新安装依赖试试
