### ISSUE TITLE
怎么提取公用样式？

### ISSUE THREAD

**Issue by momtboy** [easy-team/egg-vue-webpack-boilerplate#93]
webpack4 + vue 怎么配置提取公用样式？

使用element-ui按需加载

**Comment by hubcarl** [comment]
@momtboy 还在研究中

**Comment by hubcarl** [comment]
@momtboy @HiuYanChong   easywebpack 4.10.0 已支持公共 common.css  的提取 ，请重新 `rm -rf node_modules npm install or yarn install` 按照依赖。详细见：https://www.yuque.com/easy-team/easywebpack/common

**Comment by MrTurnRight** [comment]
怎么使用？有例子吗？

**Comment by MrTurnRight** [comment]
我加完 optimization  都没效果
